[service]
name = "smc-cloud"

[service.networking]
public = true
port = 6901
type = "http"

[service.volumes]
  [service.volumes.mt5_data]
  path = "/home/headless/.wine"
  size = "2GB"

[service.autoscaling]
min_replicas = 1
max_replicas = 1
sleep_enabled = false

[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
